
method: topk # exact, v0, muvera, topk, 
k: 15 # budget
num_rh: 8 # number of random hyperplanes to augement the embeddings with
seed: 0

query_batch_size: 512
corpus_batch_size: 5120

dtype: 'float32' # 'float16', 'bfloat16'

data:
  loader_type: "beir"
  dataset_name: "scifact"
  query_type: "forum" # "forum" or "search" if loader type is lotte

baseline:
  bucket_size: 1000 # -1 if you want everything
  seed: 17
  use_aug: False

device: 'cuda:0'

retriever:
  type: "bf" # brute force for now
  corpus_batch_size: 10240
  num_batches: -1 # if set, only use corpus batches upto num_batches
  dtype: 'float32'
  
embedder: 
  recompute_emb: False
  pretrained: True
  model_name: 'bert-base-uncased'
  save_embeddings: True
  batch_size: 1024
  #### FOR COLBERT EMBEDDER ONLY LOOK BELOW
  mode: "mem" # disk or mem
  type: 'BERT'
  mv_type: "colbertv2-plaid" # "colbertv2-base", "colbertv2-plaid", "xtr-base"
  emb_dim: 128
  query_batch_size: null
  num_queries: null # for timing analysis

muvera:
  num_repetitions: 20
  num_simhash_projections: 5
  projection_dimension: 20
  final_projection_dimension: 2560
  fresh_start: False

submodlib:
  path_suffix: null
  stop_if_zero_gain: True
  epsilon: 0.1 # ltl, lazy and stochastic greedy
  mega_q_batch_size: 100

load_state: False # if True, load the state from the path specified in the state_saver

