k: 5
colbert_topk: 100
method: "disco" # see retrievalmethods.py __main__ section for method names

data:
  dataset_name: "nfcorpus"  #scifact, hotpotqa
  loader_type: "beir"
  query_type: "forum"

augment: False 
dbl_norm: True  # [:,:,-1]=0 -> normalization -> [:,:,-1] = -1 
num_rh_augment: 8
rh_num : -1
threshold: 1
generate_new_rh: False
# RH_file: "experimemts/temp"

parallelization: "thread" # "proc" or "thread" or "none"

save_intermediate: False # save all index/scores at intermediate steps
save_full_embs: False # save full (uncompressed) embeddings for all queries/documents

index: False
overwrite_index: False # False, True, 'reuse', 'resume', "force_silent_overwrite"


colbert:
  nbits: 2 
  save_full_embs: False #TODO: remove redundancy 
  normalize_q : True # Normalise augmented queries before sending over to colbert

# only valid for disco
disco:
  rerank_internal: False ## rerank on the colbert score
  ## rerank_internal -> rerank on compressed embeddings, top-1 (reranking)
  rerank_external: True ## rerank by us on the external score

  # internal False, external True -> get ncells -> all candidates (after w) -> return from colbert -> we do reranking
  # internal True, external False -> get ncells -> all candidates (after w)-> use opt_vec to compute est.score on compressed embeddings : top-1 -> compute real score for that id to update opt_vec
  # "double reranking" internal True, external True -> get ncells -> all candidates (after w) -> use opt_vec to compute est.score on compressed embeddings : top-b -> compute real score -> top-1

  prune_candidates: False



embedder:
  mode: "disk"
  type: 'BERT'
  mv_type: "colbertv2-plaid" # "colbertv2-base", "colbertv2-plaid", "xtr-base"
  emb_dim: 128
  query_batch_size: null
  num_queries: null


retriever:
  type: "colbert"
  num_batches: -1 # historical reasons